---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: database-credentials
  namespace: voice-agent-backend
  labels:
    app.kubernetes.io/name: voice-agent
    app.kubernetes.io/component: database
    security.voice-agent.io/rotation-required: "true"
    security.voice-agent.io/rotation-interval: "30d"
  annotations:
    encryption.voice-agent.io/type: aes-256-gcm
    vault.hashicorp.com/agent-inject: "true"
data:
  DATABASE_URL: ${BASE64_DATABASE_URL}
  DB_USERNAME: ${BASE64_DB_USERNAME}
  DB_PASSWORD: ${BASE64_DB_PASSWORD}
  DB_SSL_CERT: ${BASE64_DB_SSL_CERT}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jwt-secret
  namespace: voice-agent-backend
  labels:
    app.kubernetes.io/name: voice-agent
    app.kubernetes.io/component: auth
    security.voice-agent.io/rotation-required: "true"
    security.voice-agent.io/rotation-interval: "7d"
  annotations:
    encryption.voice-agent.io/type: aes-256-gcm
    vault.hashicorp.com/agent-inject: "true"
data:
  JWT_SECRET: ${BASE64_JWT_SECRET}
  JWT_REFRESH_SECRET: ${BASE64_JWT_REFRESH_SECRET}
  JWT_PRIVATE_KEY: ${BASE64_JWT_PRIVATE_KEY}
  JWT_PUBLIC_KEY: ${BASE64_JWT_PUBLIC_KEY}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: google-cloud-credentials
  namespace: voice-agent-backend
  labels:
    app.kubernetes.io/name: voice-agent
    app.kubernetes.io/component: speech-to-text
    security.voice-agent.io/rotation-required: "true"
    security.voice-agent.io/rotation-interval: "90d"
  annotations:
    encryption.voice-agent.io/type: aes-256-gcm
    vault.hashicorp.com/agent-inject: "true"
data:
  GOOGLE_APPLICATION_CREDENTIALS: ${BASE64_GOOGLE_APPLICATION_CREDENTIALS}
  GOOGLE_PROJECT_ID: ${BASE64_GOOGLE_PROJECT_ID}
  GOOGLE_CLIENT_EMAIL: ${BASE64_GOOGLE_CLIENT_EMAIL}
  GOOGLE_PRIVATE_KEY: ${BASE64_GOOGLE_PRIVATE_KEY}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-credentials
  namespace: voice-agent-backend
  labels:
    app.kubernetes.io/name: voice-agent
    app.kubernetes.io/component: text-to-speech
    security.voice-agent.io/rotation-required: "true"
    security.voice-agent.io/rotation-interval: "90d"
  annotations:
    encryption.voice-agent.io/type: aes-256-gcm
    vault.hashicorp.com/agent-inject: "true"
data:
  AWS_ACCESS_KEY_ID: ${BASE64_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${BASE64_AWS_REGION}
  AWS_SESSION_TOKEN: ${BASE64_AWS_SESSION_TOKEN}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: encryption-keys
  namespace: voice-agent-backend
  labels:
    app.kubernetes.io/name: voice-agent
    app.kubernetes.io/component: encryption
    security.voice-agent.io/rotation-required: "true"
    security.voice-agent.io/rotation-interval: "30d"
  annotations:
    encryption.voice-agent.io/type: aes-256-gcm
    vault.hashicorp.com/agent-inject: "true"
data:
  MASTER_ENCRYPTION_KEY: ${BASE64_MASTER_ENCRYPTION_KEY}
  DATA_ENCRYPTION_KEY: ${BASE64_DATA_ENCRYPTION_KEY}