---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: voice-agent-monitoring
  labels:
    app: alertmanager
    part-of: voice-agent
    tier: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: '${SLACK_API_URL}'

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    route:
      group_by: ['alertname', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'slack-notifications'
      routes:
        - match:
            severity: critical
          receiver: 'slack-critical'
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 1h
        - match:
            severity: warning
          receiver: 'slack-warnings'
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h

    receivers:
      - name: 'slack-critical'
        slack_configs:
          - channel: '#voice-agent-critical'
            send_resolved: true
            title: '[CRITICAL] {{ .GroupLabels.alertname }}'
            text: "{{ range .Alerts }}\n*Alert:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Value:* {{ .Annotations.value }}\n{{ end }}"
            
      - name: 'slack-warnings'
        slack_configs:
          - channel: '#voice-agent-alerts'
            send_resolved: true
            title: '[WARNING] {{ .GroupLabels.alertname }}'
            text: "{{ range .Alerts }}\n*Alert:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Value:* {{ .Annotations.value }}\n{{ end }}"

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: voice-agent-monitoring
  labels:
    app: alertmanager
    part-of: voice-agent
    tier: monitoring
spec:
  ports:
    - name: alerts
      port: 9093
      targetPort: 9093
    - name: cluster
      port: 9094
      targetPort: 9094
  selector:
    app: alertmanager
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-storage
  namespace: voice-agent-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: voice-agent-monitoring
  labels:
    app: alertmanager
    part-of: voice-agent
    tier: monitoring
spec:
  replicas: 2
  serviceName: alertmanager
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.25.0
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --cluster.listen-address=0.0.0.0:9094
            - --cluster.peer=alertmanager-1.alertmanager:9094
            - --web.external-url=http://alertmanager.voice-agent-monitoring.svc.cluster.local:9093
          ports:
            - name: alerts
              containerPort: 9093
            - name: cluster
              containerPort: 9094
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: alerts
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: alerts
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
            - name: alertmanager-storage
              mountPath: /alertmanager
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
  volumeClaimTemplates:
    - metadata:
        name: alertmanager-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard