---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: voice-agent-monitoring
  labels:
    app: grafana
    part-of: voice-agent
    tier: monitoring
data:
  grafana.ini: |
    [server]
    root_url = http://grafana:3000
    [security]
    admin_user = admin
    [auth]
    disable_login_form = false
    [auth.basic]
    enabled = true
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/voice-agent-overview.json

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: voice-agent-monitoring
  labels:
    app: grafana
    part-of: voice-agent
    tier: monitoring
data:
  voice-agent-overview.json: |
    {
      "title": "Voice Agent Overview",
      "panels": [
        {
          "title": "Speech Recognition Accuracy",
          "type": "gauge",
          "datasource": "Prometheus",
          "targets": [{"expr": "speech_recognition_accuracy"}],
          "thresholds": {
            "steps": [
              { "value": 0, "color": "red" },
              { "value": 90, "color": "yellow" },
              { "value": 95, "color": "green" }
            ]
          }
        },
        {
          "title": "Recognition Latency",
          "type": "graph",
          "datasource": "Prometheus",
          "targets": [{"expr": "speech_recognition_duration_seconds"}]
        },
        {
          "title": "Active Connections",
          "type": "stat",
          "datasource": "Prometheus",
          "targets": [{"expr": "websocket_connections_active"}]
        },
        {
          "title": "Error Rate",
          "type": "graph",
          "datasource": "Prometheus",
          "targets": [{"expr": "rate(http_requests_total{status=~\"5..\"}[5m])"}]
        }
      ]
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: voice-agent-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: voice-agent-monitoring
  labels:
    app: grafana
    part-of: voice-agent
    tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsNonRoot: true
      containers:
        - name: grafana
          image: grafana/grafana:9.5.0
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-password
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-config
              mountPath: /etc/grafana
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: voice-agent-monitoring
  labels:
    app: grafana
    part-of: voice-agent
    tier: monitoring
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: grafana
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: voice-agent-monitoring
  labels:
    app: grafana
    part-of: voice-agent
    tier: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        version: 1
        editable: false